export const RECORDING_STATE_LABEL_TESTID = "RECORDING_STATE_LABEL_TESTID";
export const START_RECORDING_BUTTON_TESTID = "START_RECORDING_BUTTON_TESTID";
export const PAUSE_RECORDING_BUTTON_TESTID = "PAUSE_RECORDING_BUTTON_TESTID";
